In [3]:
import pandas as pd
import numpy as np
import os

In [38]:
combined = pd.concat([
    pd.read_pickle('split_data_0.pkl'),
    pd.read_pickle('split_data_1.pkl'),
    pd.read_pickle('split_data_2.pkl')
], axis=1)
display(combined)

           Adj_Close                                                        \
                AACG   AACT  AAME    AAN        AAT  ABAT       ABCB  ABCL
Date
1962-01-02       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-03       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-04       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-05       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-08       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
...              ...    ...   ...    ...        ...   ...        ...   ...
2024-09-24    0.6800  10.81  1.59  10.06  27.320000  0.87  62.340000  2.52
2024-09-25    0.7300  10.80  1.56  10.03  27.040001  0.81  61.240002  2.44
2024-09-26    0.7200  10.81  1.61  10.03  26.490000  0.94  61.459999  2.56
2024-09-27    0.7300  10.83  1.68  10.05  26.570000  0.98  61.320000  2.61
2024-09-30    0.7703  10.83  1.70   9.95  26.719999  1.07  62.389999  2.60

                                ... Std_Dev_10 Intercept_30  \
                   ABG    ABTS  ...        USM          USM
Date                            ...
1962-01-02         NaN     NaN  ...        NaN          NaN
1962-01-03         NaN     NaN  ...        NaN          NaN
1962-01-04         NaN     NaN  ...        NaN          NaN
1962-01-05         NaN     NaN  ...        NaN          NaN
1962-01-08         NaN     NaN  ...        NaN          NaN
...                ...     ...  ...        ...          ...
2024-09-24  230.240005  0.5000  ...   0.911999    27.068583
2024-09-25  231.699997  0.5000  ...   0.844619    27.097211
2024-09-26  238.210007  0.4990  ...   0.828737    27.144758
2024-09-27  244.350006  0.5130  ...   0.857791    27.193706
2024-09-30  238.589996  0.4701  ...   0.879987    27.244776

           Dates_Numeric_Coeff_30 Std_Dev_30 Intercept_60  \
                              USM        USM          USM
Date
1962-01-02                    NaN        NaN          NaN
1962-01-03                    NaN        NaN          NaN
1962-01-04                    NaN        NaN          NaN
1962-01-05                    NaN        NaN          NaN
1962-01-08                    NaN        NaN          NaN
...                           ...        ...          ...
2024-09-24               0.003074   1.740543    27.775168
2024-09-25               0.003081   1.668533    27.769113
2024-09-26               0.003092   1.590431    27.775943
2024-09-27               0.003104   1.533859    27.783507
2024-09-30               0.003116   1.476931    27.788047

           Dates_Numeric_Coeff_60 Std_Dev_60 Intercept_90  \
                              USM        USM          USM
Date
1962-01-02                    NaN        NaN          NaN
1962-01-03                    NaN        NaN          NaN
1962-01-04                    NaN        NaN          NaN
1962-01-05                    NaN        NaN          NaN
1962-01-08                    NaN        NaN          NaN
...                           ...        ...          ...
2024-09-24               0.002991   2.032184    27.274888
2024-09-25               0.002990   2.026951    27.309883
2024-09-26               0.002992   2.039233    27.352197
2024-09-27               0.002993   2.057816    27.392272
2024-09-30               0.002994   2.074660    27.435524

           Dates_Numeric_Coeff_90 Std_Dev_90
                              USM        USM
Date
1962-01-02                    NaN        NaN
1962-01-03                    NaN        NaN
1962-01-04                    NaN        NaN
1962-01-05                    NaN        NaN
1962-01-08                    NaN        NaN
...                           ...        ...
2024-09-24               0.002925   3.836414
2024-09-25               0.002933   3.719689
2024-09-26               0.002944   3.587287
2024-09-27               0.002953   3.482824
2024-09-30               0.002964   3.354762

[15794 rows x 127986 columns]

In [39]:
cn = list(x for x in combined.columns)
print(len(cn))
print(len((set(cn))))
# there are two duplicate rows to be removed.
# There is 1 column of Dates_Numeric for each source

127986
127984

In [40]:
combined[('Dates_Numeric','')]

C:\Users\matth\AppData\Local\Temp\ipykernel_30956\315632633.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  combined[('Dates_Numeric','')]

           Dates_Numeric

Date
1962-01-02        -13878 -13878 -13878
1962-01-03        -13877 -13877 -13877
1962-01-04        -13876 -13876 -13876
1962-01-05        -13875 -13875 -13875
1962-01-08        -13872 -13872 -13872
...                  ...    ...    ...
2024-09-24          9033   9033   9033
2024-09-25          9034   9034   9034
2024-09-26          9035   9035   9035
2024-09-27          9036   9036   9036
2024-09-30          9039   9039   9039

[15794 rows x 3 columns]

In [41]:
combined = combined.loc[:,~combined.columns.duplicated()].copy()

In [42]:
combined=combined.loc[combined.index<'2024-09-29',:]

In [43]:
combined.to_parquet('combined_2024-09-29.parquet')

In [3]:
combined_from_parq = pd.read_parquet('combined_2024-09-29.parquet')

In [16]:
base_dir = os.getcwd()
print(base_dir)
file_path = os.path.abspath(os.path.join(base_dir, '..'))
print(file_path)

c:\Users\matthew\codeProjects\tradingProjects\union_sif_quant_trading\data\stock_price_data
c:\Users\matthew\codeProjects\tradingProjects\union_sif_quant_trading\data

In [18]:
print(file_path+'\\company_data\\company_data_yf_2024-09-29.csv')

c:\Users\matthew\codeProjects\tradingProjects\union_sif_quant_trading\data\company_data\company_data_yf_2024-09-29.csv

In [23]:
# add market cap data
yf_company_data = pd.read_csv(file_path+'\\company_data\\company_data_yf_2024-09-29.csv',index_col=0)
display(yf_company_data)

,Market_Cap,Quote_Type,Shares,Currency,Exchange,Time_Zone
Ticker,,,,,,
A,4.254178e+10,EQUITY,287328000.0,USD,NYQ,America/New_York
AA,1.014760e+10,EQUITY,258406000.0,USD,NYQ,America/New_York
AACT,6.768750e+08,EQUITY,62500000.0,USD,NYQ,America/New_York
AAM,4.401797e+08,EQUITY,43974000.0,USD,NYQ,America/New_York
AAN,3.170855e+08,EQUITY,31550800.0,USD,NYQ,America/New_York
...,...,...,...,...,...,...
ZURA,2.595610e+08,EQUITY,63774200.0,USD,NCM,America/New_York
ZVRA,3.641152e+08,EQUITY,52617800.0,USD,NMS,America/New_York
ZVSA,2.535112e+06,EQUITY,1074200.0,USD,NCM,America/New_York
ZYME,8.824087e+08,EQUITY,71047400.0,USD,NMS,America/New_York
ZYXI,2.618754e+08,EQUITY,32330300.0,USD,NMS,America/New_York

In [6]:
# yf_company_market_cap_data = yf_company_data.loc[:,['Market_Cap']]
# yf
# yf_company_shares_data = yf_company_data.loc[:,['Shares']]
# yf_company_market_cap_data = yf_company_market_cap_data.sort_index(axis=0)
# yf_company_shares_data = yf_company_shares_data.sort_index(axis=0)
# display(yf_company_market_cap_data.head())
# display(yf_company_shares_data.head())
adj_close_slice = combined_from_parq.xs('Adj_Close',level=0,axis=1)
# adj_close_slice = adj_close_slice.sort_index(axis=1)
# display(adj_close_slice.tail())
# print(yf_company_market_cap_data.shape)
# print(yf_company_shares_data.shape)
print(yf_company_data.shape)
print(adj_close_slice.shape)
# shares_outstanding = yf_company_market_cap_data['Market_Cap'] / adj_close_slice.iloc[-1].reindex(yf_company_market_cap_data.index)
market_cap_slice = adj_close_slice.sort_index(axis=1) * yf_company_data['Shares'].sort_index(axis=0)
market_cap_slice.columns = pd.MultiIndex.from_product([['Market_Cap'], market_cap_slice.columns])

display(market_cap_slice)
combined_from_parq = pd.concat([combined_from_parq, market_cap_slice], axis=1)
display(combined_from_parq)
# display(shares_outstanding)

(6328, 6)
(15793, 6328)

              Market_Cap                                            \
                       A            AA          AACG          AACT
Date
1962-01-02           NaN  3.983857e+08           NaN           NaN
1962-01-03           NaN  4.044791e+08           NaN           NaN
1962-01-04           NaN  4.044791e+08           NaN           NaN
1962-01-05           NaN  4.037171e+08           NaN           NaN
1962-01-08           NaN  3.900061e+08           NaN           NaN
...                  ...           ...           ...           ...
2024-09-23  4.016558e+10  8.845237e+09  2.012850e+07  6.750000e+08
2024-09-24  4.076322e+10  9.504172e+09  2.172600e+07  6.756250e+08
2024-09-25  4.006502e+10  9.305200e+09  2.332350e+07  6.750000e+08
2024-09-26  4.216251e+10  1.015019e+10  2.300400e+07  6.756250e+08
2024-09-27  4.254178e+10  1.014760e+10  2.332350e+07  6.768750e+08

                                                                    \
                    AADI           AAL           AAM          AAME
Date
1962-01-02           NaN           NaN           NaN           NaN
1962-01-03           NaN           NaN           NaN           NaN
1962-01-04           NaN           NaN           NaN           NaN
1962-01-05           NaN           NaN           NaN           NaN
1962-01-08           NaN           NaN           NaN           NaN
...                  ...           ...           ...           ...
2024-09-23  4.701427e+07  7.363429e+09  4.393002e+08  3.223168e+07
2024-09-24  4.652197e+07  7.403667e+09  4.399599e+08  3.243568e+07
2024-09-25  4.676812e+07  7.376842e+09  4.395201e+08  3.182369e+07
2024-09-26  4.701427e+07  7.906634e+09  4.401798e+08  3.284368e+07
2024-09-27  4.750656e+07  7.752391e+09  4.401798e+08  3.427166e+07

                                        ...                              \
                     AAN          AAOI  ...           ZTS          ZUMZ
Date                                    ...
1962-01-02           NaN           NaN  ...           NaN           NaN
1962-01-03           NaN           NaN  ...           NaN           NaN
1962-01-04           NaN           NaN  ...           NaN           NaN
1962-01-05           NaN           NaN  ...           NaN           NaN
1962-01-08           NaN           NaN  ...           NaN           NaN
...                  ...           ...  ...           ...           ...
2024-09-23  3.174011e+08  6.199968e+08  ...  8.773325e+10  4.243648e+08
2024-09-24  3.174011e+08  7.046620e+08  ...  8.777857e+10  4.241734e+08
2024-09-25  3.164545e+08  6.782042e+08  ...  8.679967e+10  4.144113e+08
2024-09-26  3.164545e+08  6.530692e+08  ...  8.831333e+10  4.161340e+08
2024-09-27  3.170855e+08  6.056654e+08  ...  8.828614e+10  4.211108e+08

                                                                    \
                     ZUO          ZURA          ZVIA          ZVRA
Date
1962-01-02           NaN           NaN           NaN           NaN
1962-01-03           NaN           NaN           NaN           NaN
1962-01-04           NaN           NaN           NaN           NaN
1962-01-05           NaN           NaN           NaN           NaN
1962-01-08           NaN           NaN           NaN           NaN
...                  ...           ...           ...           ...
2024-09-23  1.307258e+09  2.678516e+08  7.098300e+07  3.988429e+08
2024-09-24  1.308771e+09  2.550968e+08  6.904710e+07  4.351492e+08
2024-09-25  1.302719e+09  2.493571e+08  7.937190e+07  3.970013e+08
2024-09-26  1.314823e+09  2.531836e+08  7.550010e+07  3.846361e+08
2024-09-27  1.316336e+09  2.595610e+08  7.356420e+07  3.641152e+08


                    ZVSA           ZWS          ZYME          ZYXI
Date
1962-01-02           NaN           NaN           NaN           NaN
1962-01-03           NaN           NaN           NaN           NaN
1962-01-04           NaN           NaN           NaN           NaN
1962-01-05           NaN           NaN           NaN           NaN
1962-01-08           NaN           NaN           NaN           NaN
...                  ...           ...           ...           ...
2024-09-23  2.320272e+06  5.840609e+09  9.065648e+08  2.579958e+08
2024-09-24  2.352498e+06  5.926073e+09  8.880925e+08  2.621987e+08
2024-09-25  2.395466e+06  5.931202e+09  8.888030e+08  2.583191e+08
2024-09-26  2.470660e+06  5.997864e+09  8.859611e+08  2.670483e+08
2024-09-27  2.535112e+06  6.095292e+09  8.824087e+08  2.618754e+08

[15793 rows x 6328 columns]

           Adj_Close                                                        \
                AACG   AACT  AAME    AAN        AAT  ABAT       ABCB  ABCL
Date
1962-01-02       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-03       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-04       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-05       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-08       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
...              ...    ...   ...    ...        ...   ...        ...   ...
2024-09-23      0.63  10.80  1.58  10.06  27.120001  0.89  63.709999  2.48
2024-09-24      0.68  10.81  1.59  10.06  27.320000  0.87  62.340000  2.52
2024-09-25      0.73  10.80  1.56  10.03  27.040001  0.81  61.240002  2.44
2024-09-26      0.72  10.81  1.61  10.03  26.490000  0.94  61.459999  2.56
2024-09-27      0.73  10.83  1.68  10.05  26.570000  0.98  61.320000  2.61

                               ...    Market_Cap                              \
                   ABG   ABTS  ...           ZTS          ZUMZ           ZUO
Date                           ...
1962-01-02         NaN    NaN  ...           NaN           NaN           NaN
1962-01-03         NaN    NaN  ...           NaN           NaN           NaN
1962-01-04         NaN    NaN  ...           NaN           NaN           NaN
1962-01-05         NaN    NaN  ...           NaN           NaN           NaN
1962-01-08         NaN    NaN  ...           NaN           NaN           NaN
...                ...    ...  ...           ...           ...           ...
2024-09-23  227.949997  0.490  ...  8.773325e+10  4.243648e+08  1.307258e+09
2024-09-24  230.240005  0.500  ...  8.777857e+10  4.241734e+08  1.308771e+09
2024-09-25  231.699997  0.500  ...  8.679967e+10  4.144113e+08  1.302719e+09
2024-09-26  238.210007  0.499  ...  8.831333e+10  4.161340e+08  1.314823e+09
2024-09-27  244.350006  0.513  ...  8.828614e+10  4.211108e+08  1.316336e+09

                                                                    \
                    ZURA          ZVIA          ZVRA          ZVSA
Date
1962-01-02           NaN           NaN           NaN           NaN
1962-01-03           NaN           NaN           NaN           NaN
1962-01-04           NaN           NaN           NaN           NaN
1962-01-05           NaN           NaN           NaN           NaN
1962-01-08           NaN           NaN           NaN           NaN
...                  ...           ...           ...           ...
2024-09-23  2.678516e+08  7.098300e+07  3.988429e+08  2.320272e+06
2024-09-24  2.550968e+08  6.904710e+07  4.351492e+08  2.352498e+06
2024-09-25  2.493571e+08  7.937190e+07  3.970013e+08  2.395466e+06
2024-09-26  2.531836e+08  7.550010e+07  3.846361e+08  2.470660e+06
2024-09-27  2.595610e+08  7.356420e+07  3.641152e+08  2.535112e+06


                     ZWS          ZYME          ZYXI
Date
1962-01-02           NaN           NaN           NaN
1962-01-03           NaN           NaN           NaN
1962-01-04           NaN           NaN           NaN
1962-01-05           NaN           NaN           NaN
1962-01-08           NaN           NaN           NaN
...                  ...           ...           ...
2024-09-23  5.840609e+09  9.065648e+08  2.579958e+08
2024-09-24  5.926073e+09  8.880925e+08  2.621987e+08
2024-09-25  5.931202e+09  8.888030e+08  2.583191e+08
2024-09-26  5.997864e+09  8.859611e+08  2.670483e+08
2024-09-27  6.095292e+09  8.824087e+08  2.618754e+08

[15793 rows x 134312 columns]

In [7]:
def categorize_market_cap(value):
    if value >= 200e9:
        return 'mega'
    elif 10e9 <= value < 200e9:
        return 'large'
    elif 2e9 <= value < 10e9:
        return 'mid'
    elif 250e6 <= value < 2e9:
        return 'small'
    elif 0 < value < 250e6:
        return 'micro'
    # if there isn't data
    else:
        return np.nan

In [8]:
size_category_slice = combined_from_parq.xs('Market_Cap',level=0, axis=1).map(categorize_market_cap)
size_category_slice.columns = pd.MultiIndex.from_product([['Size_Category'], size_category_slice.columns])

display(size_category_slice)

combined_from_parq = pd.concat([combined_from_parq, size_category_slice], axis=1)
display(combined_from_parq)

           Size_Category                                                 \
                       A     AA   AACG   AACT   AADI  AAL    AAM   AAME
Date
1962-01-02           NaN  small    NaN    NaN    NaN  NaN    NaN    NaN
1962-01-03           NaN  small    NaN    NaN    NaN  NaN    NaN    NaN
1962-01-04           NaN  small    NaN    NaN    NaN  NaN    NaN    NaN
1962-01-05           NaN  small    NaN    NaN    NaN  NaN    NaN    NaN
1962-01-08           NaN  small    NaN    NaN    NaN  NaN    NaN    NaN
...                  ...    ...    ...    ...    ...  ...    ...    ...
2024-09-23         large    mid  micro  small  micro  mid  small  micro
2024-09-24         large    mid  micro  small  micro  mid  small  micro
2024-09-25         large    mid  micro  small  micro  mid  small  micro
2024-09-26         large  large  micro  small  micro  mid  small  micro
2024-09-27         large  large  micro  small  micro  mid  small  micro

                          ...                                            \
              AAN   AAOI  ...    ZTS   ZUMZ    ZUO   ZURA   ZVIA   ZVRA
Date                      ...
1962-01-02    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
1962-01-03    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
1962-01-04    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
1962-01-05    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
1962-01-08    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
...           ...    ...  ...    ...    ...    ...    ...    ...    ...
2024-09-23  small  small  ...  large  small  small  small  micro  small
2024-09-24  small  small  ...  large  small  small  small  micro  small
2024-09-25  small  small  ...  large  small  small  micro  micro  small
2024-09-26  small  small  ...  large  small  small  small  micro  small
2024-09-27  small  small  ...  large  small  small  small  micro  small


             ZVSA  ZWS   ZYME   ZYXI
Date
1962-01-02    NaN  NaN    NaN    NaN
1962-01-03    NaN  NaN    NaN    NaN
1962-01-04    NaN  NaN    NaN    NaN
1962-01-05    NaN  NaN    NaN    NaN
1962-01-08    NaN  NaN    NaN    NaN
...           ...  ...    ...    ...
2024-09-23  micro  mid  small  small
2024-09-24  micro  mid  small  small
2024-09-25  micro  mid  small  small
2024-09-26  micro  mid  small  small
2024-09-27  micro  mid  small  small

[15793 rows x 6328 columns]

           Adj_Close                                                        \
                AACG   AACT  AAME    AAN        AAT  ABAT       ABCB  ABCL
Date
1962-01-02       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-03       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-04       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-05       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
1962-01-08       NaN    NaN   NaN    NaN        NaN   NaN        NaN   NaN
...              ...    ...   ...    ...        ...   ...        ...   ...
2024-09-23      0.63  10.80  1.58  10.06  27.120001  0.89  63.709999  2.48
2024-09-24      0.68  10.81  1.59  10.06  27.320000  0.87  62.340000  2.52
2024-09-25      0.73  10.80  1.56  10.03  27.040001  0.81  61.240002  2.44
2024-09-26      0.72  10.81  1.61  10.03  26.490000  0.94  61.459999  2.56
2024-09-27      0.73  10.83  1.68  10.05  26.570000  0.98  61.320000  2.61

                               ... Size_Category                              \
                   ABG   ABTS  ...           ZTS   ZUMZ    ZUO   ZURA   ZVIA
Date                           ...
1962-01-02         NaN    NaN  ...           NaN    NaN    NaN    NaN    NaN
1962-01-03         NaN    NaN  ...           NaN    NaN    NaN    NaN    NaN
1962-01-04         NaN    NaN  ...           NaN    NaN    NaN    NaN    NaN
1962-01-05         NaN    NaN  ...           NaN    NaN    NaN    NaN    NaN
1962-01-08         NaN    NaN  ...           NaN    NaN    NaN    NaN    NaN
...                ...    ...  ...           ...    ...    ...    ...    ...
2024-09-23  227.949997  0.490  ...         large  small  small  small  micro
2024-09-24  230.240005  0.500  ...         large  small  small  small  micro
2024-09-25  231.699997  0.500  ...         large  small  small  micro  micro
2024-09-26  238.210007  0.499  ...         large  small  small  small  micro
2024-09-27  244.350006  0.513  ...         large  small  small  small  micro


             ZVRA   ZVSA  ZWS   ZYME   ZYXI
Date
1962-01-02    NaN    NaN  NaN    NaN    NaN
1962-01-03    NaN    NaN  NaN    NaN    NaN
1962-01-04    NaN    NaN  NaN    NaN    NaN
1962-01-05    NaN    NaN  NaN    NaN    NaN
1962-01-08    NaN    NaN  NaN    NaN    NaN
...           ...    ...  ...    ...    ...
2024-09-23  small  micro  mid  small  small
2024-09-24  small  micro  mid  small  small
2024-09-25  small  micro  mid  small  small
2024-09-26  small  micro  mid  small  small
2024-09-27  small  micro  mid  small  small

[15793 rows x 140640 columns]

In [10]:
combined_from_parq[('Dates_Numeric','')]

Date
1962-01-02   -13878
1962-01-03   -13877
1962-01-04   -13876
1962-01-05   -13875
1962-01-08   -13872
              ...
2024-09-23     9032
2024-09-24     9033
2024-09-25     9034
2024-09-26     9035
2024-09-27     9036
Name: (Dates_Numeric, ), Length: 15793, dtype: int64

In [11]:
combined_from_parq.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 15793 entries, 1962-01-02 to 2024-09-27
Columns: 140640 entries, ('Adj_Close', 'AACG') to ('Size_Category', 'ZYXI')
dtypes: float64(134988), int64(30), object(5622)
memory usage: 16.5+ GB

In [13]:
combined_from_parq.to_pickle('all_data_processed_2024-09-28.pkl')

In [14]:
combined_from_parq.to_parquet('all_data_processed_2024-09-28.parquet')

In [15]:
combined_from_parq = combined_from_parq.loc[combined_from_parq.index>='1990-01-01',:]

In [16]:
combined_from_parq.to_pickle('all_data_processed_2024-09-28_after_1990.pkl')

In [17]:
combined_from_parq.to_parquet('all_data_processed_2024-09-28_after_1990.parquet')

In [18]:
combined_from_parq.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8752 entries, 1990-01-02 to 2024-09-27
Columns: 140640 entries, ('Adj_Close', 'AACG') to ('Size_Category', 'ZYXI')
dtypes: float64(134988), int64(30), object(5622)
memory usage: 9.2+ GB